### ISSUE TITLE
No models recording today

### ISSUE THREAD

**Issue by mikeyside** [beaston02/ChaturbateRecorder#6] opened 2017-07-26 16:11 UTC
Hi,

This seems to affect chaturbate only as MFC is working.
I seem to have run into an issue- the code is running but no models are being detected.

Have chaturbate made changes to there site?

**Comment by beaston02** [comment] 2017-07-26 18:01
Are you running the latest version (updated yesterday)? Which OS are you on? 

I only did limited testing on the release I did yesterday, on Mac and Ubuntu. It's possible I missed something although it did find and record models on both of those systems.

**Comment by mikeyside** [comment] 2017-07-26 22:03
Using Ubuntu 16.04 
Using an old version. What are the changes of the latest release? Not sure what’s going on.

**Comment by beaston02** [comment] 2017-07-26 22:18
For the most part, the changes were addressing the "too many open files" error. 

There haven't been any changes I'm aware of to chaturbate. I tested again when I got home today and it is still working fine for me. 

I would suggest downloading the current version and seeing if it still does not work. In the current version I added a "getModels.py" file which can be ran on its own also. It would simply print a list of all the online models. If that works, but the recordings still do not start, then that will narrow down where the problem may be. 

I'll see if I can push myself to stop being so lazy and implement some logging to help troubleshoot these problems also.

**Comment by mikeyside** [comment] 2017-07-27 07:50
I will update - I have had some recordings but mostly it’s doing nothing which is odd.

Seems to have coincided with some os updates so I wonder if it broke a component.

**Comment by Hampster82** [comment] 2017-07-27 09:56
I was actually just testing some stuff and noticed that some models don't seem to get captured on my end either.
Their names show up in the big old list that "getModels.py" generates, so it doesn't seem to be that.
I didn't do a lot of testing to see how wide of a problem it is on my end, but I'm unable to cap alycetn or perfect_cutie just as an example.

No idea if this is the same as mikeyside's problem.

**Comment by mikeyside** [comment] 2017-07-27 12:47
I've updated and still the same issues - stand alone "getModels.py" returns a list of all online models.

However no recording takes place.

I thought I would exclude any os weirdness and setup a new vm on google cloud compute - same issue no recordings.

Is it possible Google cloud IP's are being blocked? Seems unlikely as the getModels.py works.

**Comment by beaston02** [comment] 2017-07-27 12:51
Could you do me a favor and comment out (add "#" to the beginning of the line) the lines 19, 63, 64, and 65. These should be the "try" and "except" lines from startRecording function. Im hoping that will cause it to throw an error that might give me some insight

**Comment by Hampster82** [comment] 2017-07-27 14:18
Commented those lines out and it didn't seem to affect the script running at all. No errors, the models that I'm able to cap work as before.

**Comment by Hampster82** [comment] 2017-07-27 14:54
I think I may have found the problem. For some reason only the very last model from the wishlist is being captured. If that model happens to be offline, then no one is getting captured.

**Comment by beaston02** [comment] 2017-07-27 15:11
That is definitely something I could have missed in my testing. I don't run this script myself, so when I'm yes girl, I generally just add a model who happens to be online and have figured it was working when that model starts recording. You mentioned removing the try statement didn't throw an error which made me believe it was never trying to start the models.

I will test this theory when I get w chance and hopefully have it confirmed and corrected today. I'll see about adding some logging also, so we can avoid all this troubleshooting blindly! 

Thank you for the info.

**Comment by beaston02** [comment] 2017-07-27 18:38
I had a short break where I was able to do a little more testing. I tested your theory (@Hampster82 ) of the last model being on the list needing to be online, and I wasn't able to reproduce that myself. I added multiple models, some who are online, others who are not, moved them in different orders in the list... For whatever reason, I am having 100% accuracy on it starting the models who are on the list no matter what I have tried. I haven't built a huge list, but I have grabbed different models from different pages (as in not all from the first page of the directory of chaturbate). I also haven't tried with a huge list. I went up to 6 models and that was it at the moment (again, didn't have a ton of time). 

I am still rather new with python, and I need some time to sit down and familiarize myself with implementing logging, but I will try to do that later today, or in the next couple of days when time allows it. I did make a few changes, but I don't think its anything that is going to make a difference. The changes were more to clean things up a bit, and what I assume will make things run a bit more efficiently. I will upload the file as I am using it now, and you can feel free to download it and try it yourself if you would like, although again, I don't think I made any significant changes, but some changes to how it compares the list of online models and the list on the wishlist, so it may be worth a shot. 

Oh, also, I tested on both mac, and Ubuntu 14.04.4  (server (headless))

I will keep you updated when I have time to get more work done. 

Thanks again.

**Comment by Hampster82** [comment] 2017-07-28 07:34
I'm on Windows 10 with Python 3.6.2

Well, whatever changes you made, it seems to be working now, at least over here.  Hopefully mikeyside can chime in as well.

**Comment by SearchAndDestroy** [comment] 2017-07-28 09:51
I just cloned the repro and it's working great so far for me as well. I am on Win10 with python 3.6.2
Is there any way to reload the wanted.txt file automatically so that any updates are taken into account?

**Comment by beaston02** [comment] 2017-07-28 12:58
That's great to hear. Thank you both for reporting back. 

@SearchAndDestroy, the script reloads and reads the wanted.txt file prior to each check. Is it not recording models you have newly added to the list?

**Comment by SearchAndDestroy** [comment] 2017-07-28 13:01
@beaston02 Nice to know it rereads the file :) I was just wondering as I just started to use the script.

**Comment by beaston02** [comment] 2017-07-28 13:07
@SearchAndDestroy, good to hear! I hope you enjoy it!

**Comment by SearchAndDestroy** [comment] 2017-07-28 15:35
@beaston02 I am enjoying it. I have not yet watched any of the recordings but I will later tonight.
Just one small bug: you can have a model's name more that once in the wanted and it will start recording multiple times. Maybe sort the list and remove duplicates and warn about it?

**Comment by beaston02** [comment] 2017-07-29 04:55
Thank you for the info @SearchAndDestroy. I updated the script to remove duplicates in the list. I did not add a warning because I don't see it as a huge deal, and to be honest, didn't want to spend the time coding that in :) haha. I may add that later, but for now, it should not start duplicate recordings for a model who appears more than once. 

Im am going to go ahead and close this issue as it seems the originally reported issue has been solved. Please open a new issue for anything else which may come up, or if anyone is still having this issue.

**Closed by beaston02** 2017-07-29 04:55 UTC
