### ISSUE TITLE
Code Occasionally Gets Stuck Getting Models

### ISSUE THREAD

**Issue by Miatrix** [beaston02/ChaturbateRecorder#2] opened 2017-06-03 07:51 UTC
Code Occasionally Gets Stuck Getting Models. Last time after changing the time from 5 seconds to 30 seconds it got stuck after around 2 minutes.

Here is the stack trace when I kill it:
`Process ForkPoolWorker-137:
Traceback (most recent call last):
  File "ChaturbateRecorder.py", line 114, in <module>
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 342, in get
    with self._rlock:
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 343, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
    online = checker.getModels()
  File "ChaturbateRecorder.py", line 34, in getModels
    online = p.map(getOnlineModels, pages)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 602, in get
    self.wait(timeout)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 599, in wait
    self._event.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 549, in wait
    signaled = self._cond.wait(timeout)
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
KeyboardInterrupt

^CProcess ForkPoolWorker-139:
Process ForkPoolWorker-140:
Exception ignored in: <module 'threading' from '/usr/lib/python3.5/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 1288, in _shutdown
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 342, in get
    with self._rlock:
  File "/usr/lib/python3.5/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib/python3.5/multiprocessing/queues.py", line 343, in get
    res = self._reader.recv_bytes()
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 216, in recv_bytes
    buf = self._recv_bytes(maxlength)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/usr/lib/python3.5/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
KeyboardInterrupt
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
`

**Comment by beaston02** [comment] 2017-06-03 14:57
Thank you for posting. I forgot to limit the number of attempted checks on a page before giving up. I believe this was causing the issue. It should now be fixed. 

I also added a variable "interval" which can set to change the time between checks. I set it to 20, which is what I meant to have in the range, but was using 5 seconds for testing, and apparently forgot to change it back before posting. 

Let me know if you continue to have the issue, if I don't hear anything in a few days, Ill mark it closed.

**Comment by Miatrix** [comment] 2017-06-03 19:25
It ran for a bit but I got the following error now and then it appears to stop processing but is still running.  Just not checking models anymore
`Traceback (most recent call last):
  File "/usr/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3.5/http/client.py", line 1252, in connect
    super().connect()
  File "/usr/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "ChaturbateRecorder.py", line 53, in getOnlineModels
    result = urllib.request.urlopen(URL)
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 466, in open
    response = self._open(req, data)
  File "/usr/lib/python3.5/urllib/request.py", line 484, in _open
    '_open', req)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 1297, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.5/urllib/request.py", line 1256, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "ChaturbateRecorder.py", line 123, in <module>
    online = checker.getModels()
  File "ChaturbateRecorder.py", line 37, in getModels
    online = p.map(getOnlineModels, pages)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
`

**Comment by beaston02** [comment] 2017-06-03 23:56
Thank you for the update. I am looking into this, and trying to see if I can recreate the issue. Ill keep you updated.

**Comment by Aussi25** [comment] 2017-06-07 03:46
Just wanted to say thanks for sharing this! Unfortunately i'm suffering from the exact same issue. Tried python 3.5.2 as well as 3.6.1 makes no difference, Debian Jessie.

**Comment by beaston02** [comment] 2017-06-20 02:21
Sorry for the slow response. I just posted an updated script. Please let me know if you continue to have issues. 

I also added a config file so make sure to set your values inside there after updating.

**Comment by beaston02** [comment] 2017-06-21 17:58
Shortly after posting the last update, I had the issue come back again. 

Current update should now fix the issue.

**Comment by Aussi25** [comment] 2017-06-24 22:11
Thanks for the update! Unfortunately a new issue occurs. Recording seems to work for a little while then:
`File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='chaturbate.com', port=443): Max retries exceeded with url: /couple-cams/?page=48 (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f35f56faac8>: Failed to establish a new connection: [Errno 24] Too many open files',))

Traceback (most recent call last):
  File "ChaturbateRecorder.py", line 124, in <module>
OSError: [Errno 24] Too many open files: '/home/user/ChaturbateRecorder/wanted.txt'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 661, in exec_module
  File "<frozen importlib._bootstrap_external>", line 766, in get_code
  File "<frozen importlib._bootstrap_external>", line 818, in get_data
OSError: [Errno 24] Too many open files: '/usr/lib/python3/dist-packages/apport/__init__.py'

Original exception was:
Traceback (most recent call last):
  File "ChaturbateRecorder.py", line 124, in <module>
OSError: [Errno 24] Too many open files: '/home/user/ChaturbateRecorder/wanted.txt'`

**Comment by creampeaches** [comment] 2017-07-22 10:21
Same has happened for me too! "too many open files" error message

**Comment by beaston02** [comment] 2017-07-22 16:17
Thanks for posting. 

Ive searched long and hard for a solution for this. It seems to be an issue with urllib (the standard way for getting website data in python). Although you may get the error with non website data (like opening the wanted.txt) it is ultimately being caused by urllib leaving each connection open as a file. I have yet to find a proper solution for this, but Im still looking into it. The only one Ive currently found is to set the number of files allowed to be open by a single process. on unix systems, you can see the current limit by running `ulimit -n`. You can adjust it by running `ulimit -n #` where "#" is the new value. My FreeNAS jail was defaulted to > 1.8 million. You can crank that number up to whatever you would like, although in time, it will eventually hit that number and throw the same error.

**Comment by beaston02** [comment] 2017-07-26 00:20
I just made some changes to fix this problem. I haven't done extensive testing, but with one model recording, and after about 30 minutes on one of my ubuntu servers, its showing 6 files open by the process (would have been hundreds, if not > 1000 by now using the old method). 

Please clone the current version, and let me know if you continue to have any problems.

**Comment by beaston02** [comment] 2017-07-29 04:57
Due to no more reports of this issue, I am going to close this.

**Closed by beaston02** 2017-07-29 04:57 UTC
